const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const U=require('../docs/active-universe.js'),UI=require('../docs/decision-experience.js'),Q=require('../docs/quality-details.js');
function fixture(){
 const day='2026-10-02',stamp=day+'T22:51:40+09:00';
 const d={decision_mode:'SHADOW',latest_decision_as_of:day,updated_at:stamp,run_status:'SHADOW_COMMITTED',run_id:'RUN_20261002_1700',shadow_validation:{run_count:7,security_check_count:42,production_candidate:false},securities:[...U.CODES,'5805'].map((code,i)=>({code,security_id:'SEC_JP_'+code,ticker:code+'.T',name:code==='5805'?'SWCC':U.NAMES[i],price:100+i,as_of:day,shadow_action:code==='6841'||code==='5805'?'WAIT':'HOLD',source_evidence:{crosscheck_match:true},source_gate_reason:'SHADOW_SOURCE_MATCH',data_quality:'PROVISIONAL',outlook:{'1':{direction:'UP',confidence:'LOW',analog:{sample_count:40,median_return_pct:0.2}}},next_conditions:[{label:code==='5805'?'参考：13,300円回復':'週足悪化なし',status:'PENDING'}]}))};
 const c={market:'JAPAN',timestamps:{market_as_of:day,calculated_at:stamp},data_quality:{data_state:'FRESH',qc_state:'WARN'},decision_items:d.securities.map(s=>({subject_id:s.security_id,ticker:s.ticker,subject_label:s.name,as_of:day,reason_summary:s.next_conditions.map(x=>x.label)}))};
 return {d,c};
}
function model(d,c){return UI.makeModel(d,c,{now:new Date('2026-10-04T05:00:00Z'),sourceState:s=>s.source_evidence?.crosscheck_match===true?'PASS':'PENDING'});}
test('public active scope is exactly the approved Core config-v3 universe',()=>{assert.deepEqual(U.CODES,['6841','6954','3038','9432','1812']);assert.equal(U.VERSION,'JP-ACTIVE-20261004-v3');assert.equal(UI.CODES,U.CODES);});
test('old six-security snapshot is projected without mutating any saved evidence',()=>{const {d,c}=fixture(),before=JSON.stringify({d,c}),p=U.project(d,c);assert.equal(p.snapshot.securities.length,5);assert.equal(p.common.decision_items.length,5);assert.equal(JSON.stringify({d,c}),before);assert.equal(p.snapshot.shadow_validation,d.shadow_validation);assert.equal(p.common.data_quality,c.data_quality);for(const s of p.snapshot.securities)assert.equal(s,d.securities.find(x=>x.code===s.code));});
test('existing five-security snapshot is idempotent and loses no fields',()=>{const {d,c}=fixture(),p=U.project(d,c);assert.deepEqual(U.project(p.snapshot,p.common),p);});
test('raw legacy and new scoped inputs produce the same five-stock summary',()=>{const {d,c}=fixture(),p=U.project(d,c),a=model(d,c),b=model(p.snapshot,p.common);assert.equal(a.summary,'保有継続 4 / 待機 1');assert.equal(a.summary,b.summary);assert.equal(a.pass,5);assert.equal(a.cMatch,true);assert.equal(a.qc,'WARN');assert.equal(a.referenceOnly,true);});
test('retired name and conditions do not leak into consultation or quality reasons',()=>{const {d,c}=fixture(),m=model(d,c);assert.doesNotMatch(UI.promptFor(m),/SWCC|5805|13,300/);assert.doesNotMatch(Q.detailHtml('qc',m,c),/SWCC|5805|13,300/);assert.throws(()=>UI.promptFor(m,'5805'),/対象銘柄/);});
test('prices, actions, forecasts and conditions for retained stocks are unchanged',()=>{const {d,c}=fixture(),m=model(d,c);for(const r of m.rows){const s=d.securities.find(x=>x.code===r.code);assert.equal(r.price,s.price);assert.equal(r.action,s.shadow_action);assert.deepEqual(r.source.outlook,s.outlook);assert.deepEqual(r.source.next_conditions,s.next_conditions);}});
test('active missing row is not hidden by retirement',()=>{const {d,c}=fixture();d.securities=d.securities.filter(s=>s.code!=='1812');const m=model(d,c);assert.equal(m.pass,4);assert.equal(m.pending,1);assert.equal(m.rows.length,5);assert.equal(m.attention,true);});
test('unknown identity and malformed retired identity are never silently excluded',()=>{const {d,c}=fixture();d.securities.push({code:'9999',security_id:'SEC_JP_9999'});assert.equal(model(d,c).unexpected,1);d.securities.push({code:'5805',security_id:'SEC_JP_6841'});assert.equal(model(d,c).unexpected,2);});
test('active duplicate and Common date mismatch still fail closed',()=>{const {d,c}=fixture();d.securities.push({...d.securities[0]});assert.equal(model(d,c).pass,4);c.timestamps.calculated_at='2026-10-01T00:00:00+09:00';assert.equal(model(d,c).cMatch,false);});
test('quality tiles remain six topics while security denominators become five',()=>{const {d,c}=fixture(),m=model(d,c),s=UI.qualityHtml(m);assert.equal((s.match(/data-quality-detail=/g)||[]).length,6);assert.match(s,/5\/5一致/);assert.doesNotMatch(s,/6\/6/);assert.match(Q.detailHtml('sources',m,c),/対象5銘柄/);});
test('source projection is not network or persistent data deletion',()=>{const s=fs.readFileSync(require.resolve('../docs/active-universe.js'),'utf8');assert.doesNotMatch(s,/\bfetch\s*\(|localStorage|indexedDB|caches\.|sendBeacon|writeText/);});
test('committed public data retains every original value for currently active rows',()=>{const root=require('node:path').join(__dirname,'../docs/data/'),d=JSON.parse(fs.readFileSync(root+'app_snapshot.json','utf8')),c=JSON.parse(fs.readFileSync(root+'common_snapshot.json','utf8')),before=JSON.stringify([d,c]),p=U.project(d,c);assert.deepEqual(p.snapshot.securities,d.securities.filter(s=>!U.isRetired(s)));assert.equal(JSON.stringify([d,c]),before);assert.equal(p.snapshot.updated_at,d.updated_at);assert.deepEqual(p.snapshot.shadow_validation,d.shadow_validation);});
